name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa 51.20.92.115{{ secrets.EC2_HOST }} "
            cd D:\New folder\Ai-whatsapp-assistantt 
            git pull origin main
            npm install
            pm2 restart app
          "
