name: Deploy AI WhatsApp Assistant

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          # Ensure the SSH private key is saved in the correct location
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Deploy commands
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@3.8.119.42 << 'EOF'
            cd /path/to/your/app
            git pull origin main
            docker-compose up -d  # Or any other deployment command
          EOF

